<!DOCTYPE html>
<html>
<head><title>Daily Report</title></head>
<body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6; background: #f8fafc; margin:0; padding:0;">
    <div style="max-width:600px; margin:30px auto; background:#fff; border-radius:10px; overflow:hidden; box-shadow:0 2px 8px rgba(0,0,0,0.07);">
        <div style="background:#0f172a; padding:30px; text-align:center;">
            <h2 style="color:#d4af37; margin:0;">Bella Vista Lodge</h2>
            <p style="color:#94a3b8; margin:5px 0 0 0;">Daily Performance Report</p>
        </div>
        <div style="padding:30px;">
            <p>Hello,</p>
            <p>Here is the daily summary for <strong>{{ $reportDate }}</strong>:</p>

            <table style="width:100%; border-collapse:collapse; margin:20px 0;">
                <tr style="background:#f1f5f9;">
                    <td style="padding:14px 16px; font-weight:bold; border-radius:6px 0 0 6px;">📅 Total Bookings</td>
                    <td style="padding:14px 16px; font-size:1.3rem; font-weight:bold; color:#3b82f6; border-radius:0 6px 6px 0;">{{ $totalBookings }}</td>
                </tr>
                <tr>
                    <td style="padding:14px 16px; font-weight:bold;">💰 Total Revenue</td>
                    <td style="padding:14px 16px; font-size:1.3rem; font-weight:bold; color:#22c55e;">TZS {{ number_format($totalRevenue, 2) }}</td>
                </tr>
                <tr style="background:#f1f5f9;">
                    <td style="padding:14px 16px; font-weight:bold; border-radius:6px 0 0 6px;">🏨 Occupancy Rate</td>
                    <td style="padding:14px 16px; font-size:1.3rem; font-weight:bold; color:#f59e0b; border-radius:0 6px 6px 0;">{{ $occupancyRate }}%</td>
                </tr>
            </table>

            <p style="color:#64748b; font-size:0.9rem;">This report was automatically generated by the Bella Vista Lodge system. To view the full report, log in to the admin panel.</p>
        </div>
        <div style="background:#f8fafc; padding:16px; text-align:center; font-size:0.8rem; color:#94a3b8; border-top:1px solid #e2e8f0;">
            &copy; {{ date('Y') }} Bella Vista Lodge. All rights reserved.
        </div>
    </div>
</body>
</html>
